# Generated by Django 3.0.5 on 2022-11-22 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='cover_photo'),
        ),
    ]
